"""add column status table apartament

Revision ID: 43da1d3daa64
Revises: 5e3344815d26
Create Date: 2024-09-21 13:59:45.681870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43da1d3daa64'
down_revision: Union[str, None] = '5e3344815d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix__status_id', table_name='status')
    op.drop_table('status')
    op.add_column('apartments', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'status')
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('change_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='status_apartment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pk__status')
    )
    op.create_index('ix__status_id', 'status', ['id'], unique=False)
    # ### end Alembic commands ###
