"""add column rooms

Revision ID: a12ed0e639e3
Revises: cda2f1eb0c42
Create Date: 2024-09-17 21:25:32.820359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12ed0e639e3'
down_revision: Union[str, None] = 'cda2f1eb0c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('rooms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'rooms')
    # ### end Alembic commands ###
