"""create table

Revision ID: b8ded017ab5f
Revises: 
Create Date: 2024-09-17 18:38:03.111466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ded017ab5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('tg_id', name=op.f('uq__users__tg_id'))
    )
    op.create_index(op.f('ix__users_id'), 'users', ['id'], unique=False)
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('photos', sa.String(length=1000), nullable=True),
    sa.Column('characteristics', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('apartments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__apartments'))
    )
    op.create_index(op.f('ix__apartments_id'), 'apartments', ['id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('booking_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('booking_apartment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('booking_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__booking'))
    )
    op.create_index(op.f('ix__booking_id'), 'booking', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('status_apartment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__status'))
    )
    op.create_index(op.f('ix__status_id'), 'status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix__booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix__apartments_id'), table_name='apartments')
    op.drop_table('apartments')
    op.drop_index(op.f('ix__users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
